services:
  - type: web
    name: your-flask-app
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: EBAY_APP_ID
        sync: false
